<?php
/**
 * Created by PhpStorm.
 * User: gases
 * Date: 28.07.18
 * Time: 14:39
 */

require_once 'Page.php';

class Cached extends Page
{
    protected $expires;
    protected $store;

    public function __construct($title = '', $content = '', $footer = '', $expires = 0)
    {
        parent::__construct($title, $content, $footer);
        $this->expires = $expires;

        $this->set($this->id('title'), $title);
        $this->set($this->id('content'), $content);
        $this->set($this->id('footer'), $footer);
    }

    protected function isCached($key)
    {

    }

    protected function set($key, $value, $forse = 0)
    {

    }

    protected function get($key)
    {

    }

    public function id($name)
    {
        die('By, by...');
    }

    public function title()
    {
        return parent::title(); // TODO: Change the autogenerated stub
    }

    public function content()
    {
        return parent::content(); // TODO: Change the autogenerated stub
    }

    public function footer()
    {
        return parent::footer(); // TODO: Change the autogenerated stub
    }
}