<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

mail(
    "very.nice@ukr.net",
    "Mail robot php",
    "Hello!\nThis is autogenerated message - <b>please, do not reply!</b>",
    join("\r\n", array(
        "From: webmaster@$_SERVER[SERVER_NAME]",
        "Reply-To: webmaster@$_SERVER[SERVER_NAME]",
        "X-Mailer: PHP/".phpversion()
    ))
);
echo '<pre>';
print_r($_SERVER);
echo '</pre>';